### MEKTEP.PRO

[Тел.: +996554202905](tel:+996554202905)
[Школы](https://univer.mektep.pro/mektep)
[Университеты](https://univer.mektep.pro/univer)
[Колледжи](https://univer.mektep.pro/college)
[IT Курсы](https://univer.mektep.pro/it)
[Курсы](https://univer.mektep.pro/kurs)
[Детские садики](https://univer.mektep.pro/sadik)
[Учеба за рубежом](https://univer.mektep.pro/abroad)
[Школы](https://univer.mektep.pro/kz)
[Кыргызча](https://univer.mektep.pro/?hl=ky)
[Русский](https://univer.mektep.pro/?hl=ru)
[+996554202905](tel:+996554202905)